[shell]
program = "/bin/zsh"
args = ["-l"]

[colors.primary]
background = "0x000000"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[selection]
save_to_clipboard = true

[window]
dynamic_title = false
title = "Terminal"

[window.padding]
x = 0
y = 0

[[hints.enabled]]
command = ""
hyperlinks = true
mouse.enabled = false
